//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by FASTINST.RC
//
#define IDS_CAPTION                     1
#define IDD_PROGRESS                    101
#define IDC_PROGRESS                    1000
#define IDC_CAPTION                     1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
