// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions (including VB)

#ifdef __cplusplus
extern "C" {
#endif

#include <setupx.h>

#ifdef __cplusplus
}
#endif

